# Generated by Django 6.0.4 on 2026-04-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('intent', models.CharField(max_length=50)),
                ('entities', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('steps', models.JSONField(default=list)),
                ('whatsapp_msg', models.TextField()),
                ('email_msg', models.TextField()),
                ('sms_msg', models.TextField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
